[package]
name = "tinyurl"
version = "0.1.0"
authors = ["Valerio Casalino <casalinovalerio.cv@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10"
clap = "2.33"
tokio = { version = "0.2", features = ["macros"] }
